export class Building {
  constructor(
    public readonly id: string,
    public readonly ff: string,
    public readonly typeUnit: string,
    public readonly code: string,
    public readonly jAdmin: string,
    public readonly communities: string,
    public readonly address: string,
    public readonly presPhone: string,
    public readonly receptionMobile: string,
    public readonly internalRegulations: string,
    public readonly kashio: string,
    public readonly account: string,
    public readonly cci: string,
    public readonly accountName: string,
    public readonly mobileBankingName: string,
    public readonly agent: string,
    public readonly lateFees: string,
    public readonly bank: string,
    public readonly taxAddress: string,
    public readonly businessName: string,
    public readonly ruc: string,
  ) { }
}
